### ISSUE TITLE
As a Pick3 Lottery user, I want to know when a winning number is not available for a particular drawing time so that I know when to check for winning number again.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/pick3-lottery-web-scraper#14]

**Comment by kalexmills** [comment]
Plan is to provide a JSON object to the user which contains 

1) A user-friendly message, and
2) the ISO-8601 date when the drawing will be done.

Something like this:
{
 "message": "Winning number not yet available. Check again after 7/20/2018 5:00pm",
 "nextAvailable": "2018-07-20T17:00:00+00:00"
}

**Comment by kalexmills** [comment]
Actually, I need to change the contract of WebScraper::findDayWinningNumber(formattedDrawingDate) so that it throws an error if the numbers were not found.

Either that or these methods need to return -1 (zero is not acceptable, since 0 0 0 is a valid number).

@pouncilt I am blocked on this question for now.
